services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf 
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"] 

  coordinator:
    build:
      context: ./backend/coordinator
    container_name: coordinator
    ports:
      - "5000:5000"
    depends_on:
      - redis

  monitoring:
    build:
      context: ./monitoring
    container_name: monitoring
    ports:
      - "5001:5001"
    depends_on:
      - redis

  pc-kevin:
    build:
      context: ./backend/worker
    container_name: pc-kevin
    environment:
      - WORKER_ID=pc-kevin
      - WORKER_IP=172.24.92.26 
      - WORKER_PORT=5002
      - MONITORING_URL=http://172.24.92.26:5001
    depends_on:
      - redis
      - monitoring

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"  
    depends_on:
      - monitoring