services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  coordinator:
    build:
      context: ./backend/coordinator
    container_name: coordinator
    ports:
      - "5000:5000"
    depends_on:
      - redis

  worker:
    build:
      context: ./backend/worker
    container_name: worker
    depends_on:
      - redis
    restart: always