services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  coordinator:
    build:
      context: ./backend/coordinator
    container_name: coordinator
    ports:
      - "5000:5000"
    depends_on:
      - redis

  monitoring:
    build:
      context: ./monitoring
    container_name: monitoring
    ports:
      - "5001:5001"
    depends_on:
      - redis

  worker-1:
    build:
      context: ./backend/worker
    container_name: worker-1
    environment:
      - WORKER_ID=worker-1
      - WORKER_IP=127.0.0.1
      - WORKER_PORT=5002
      - MONITORING_URL=http://monitoring:5001
    depends_on:
      - redis
      - monitoring

  worker-2:
    build:
      context: ./backend/worker
    container_name: worker-2
    environment:
      - WORKER_ID=worker-2
      - WORKER_IP=127.0.0.1
      - WORKER_PORT=5003
      - MONITORING_URL=http://monitoring:5001
    depends_on:
      - redis
      - monitoring