services:
  pc-justin:
    build:
      context: ./backend/worker
    container_name: pc-justin
    environment:
      - WORKER_ID=pc-justin
      - WORKER_IP=172.24.98.198                  #IP maquina en remoto
      - WORKER_PORT=5003
      - MONITORING_URL=http://172.24.92.26:5001  # IP de la máquina principal
      - REDIS_HOST=172.24.92.26                  # IP de la máquina principal